/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    pages: Page
    models: Model
    banners: Banner
    'maintenance-plans': MaintenancePlan
    locations: Location
    services: Service
    'nav-items': NavItem
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    models: ModelsSelect<false> | ModelsSelect<true>
    banners: BannersSelect<false> | BannersSelect<true>
    'maintenance-plans': MaintenancePlansSelect<false> | MaintenancePlansSelect<true>
    locations: LocationsSelect<false> | LocationsSelect<true>
    services: ServicesSelect<false> | ServicesSelect<true>
    'nav-items': NavItemsSelect<false> | NavItemsSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    'site-settings': SiteSetting
    header: Header
    footer: Footer
    'home-page': HomePage
  }
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>
    header: HeaderSelect<false> | HeaderSelect<true>
    footer: FooterSelect<false> | FooterSelect<true>
    'home-page': HomePageSelect<false> | HomePageSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  role: 'admin' | 'editor'
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  title: string
  description?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number
  title: string
  /**
   * Ruta sin diagonales, por ejemplo: nosotros
   */
  slug: string
  layout: (
    | {
        eyebrow?: string | null
        title: string
        description?: string | null
        image?: (number | null) | Media
        ctaLabel?: string | null
        ctaHref?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'hero'
      }
    | {
        heading?: string | null
        body: string
        alignment?: ('left' | 'center') | null
        id?: string | null
        blockName?: string | null
        blockType: 'content'
      }
    | {
        media: number | Media
        caption?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'mediaBlock'
      }
    | {
        heading?: string | null
        items: {
          title: string
          description?: string | null
          image?: (number | null) | Media
          href?: string | null
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'cards'
      }
    | {
        heading?: string | null
        items: {
          question: string
          answer: string
          id?: string | null
        }[]
        id?: string | null
        blockName?: string | null
        blockType: 'accordion'
      }
    | {
        heading: string
        description?: string | null
        label: string
        href: string
        id?: string | null
        blockName?: string | null
        blockType: 'callToAction'
      }
  )[]
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    canonicalUrl?: string | null
    noIndex?: boolean | null
    noFollow?: boolean | null
    socialImage?: (number | null) | Media
    /**
     * JSON-LD controlado para datos estructurados de Schema.org.
     */
    structuredData?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number
  name: string
  slug: string
  code?: string | null
  type?: ('Camion' | 'Cabezal' | 'Vagoneta') | null
  passengers?: string | null
  transmission?: string | null
  year?: number | null
  priceBase?: number | null
  promoPrice?: number | null
  description?: string | null
  image?: (number | null) | Media
  /**
   * URL alternativa si no hay archivo en Media
   */
  urlImage?: string | null
  urlTechSpec?: string | null
  gallery?:
    | {
        image: number | Media
        type?: string | null
        isMain?: boolean | null
        isActive?: boolean | null
        id?: string | null
      }[]
    | null
  order?: number | null
  enable?: boolean | null
  isProd?: boolean | null
  isDevelop?: boolean | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    canonicalUrl?: string | null
    noIndex?: boolean | null
    noFollow?: boolean | null
    socialImage?: (number | null) | Media
    /**
     * JSON-LD controlado para datos estructurados de Schema.org.
     */
    structuredData?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number
  section: 'Inicio' | 'PlanesMantenimiento'
  alt?: string | null
  type?: ('IMAGE' | 'VIDEO') | null
  image?: (number | null) | Media
  imageMobile?: (number | null) | Media
  /**
   * URL alternativa
   */
  bannerUrl?: string | null
  bannerUrlMobile?: string | null
  videoUrl?: string | null
  videoMobileUrl?: string | null
  order?: number | null
  enable?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-plans".
 */
export interface MaintenancePlan {
  id: number
  name: string
  code?: string | null
  image?: (number | null) | Media
  image2?: (number | null) | Media
  planImageUrl?: string | null
  planImageUrl2?: string | null
  order?: number | null
  enabled?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number
  name: string
  address?: string | null
  phone?: string | null
  branchHours?: string | null
  workshopHours?: string | null
  googleLink?: string | null
  wazeLink?: string | null
  appleMapsLink?: string | null
  /**
   * Una por línea
   */
  specialities?: string | null
  isBranchOffice?: boolean | null
  isRepairShop?: boolean | null
  isActive?: boolean | null
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number
  title: string
  image?: (number | null) | Media
  /**
   * URL alternativa de imagen
   */
  url?: string | null
  link?: string | null
  page?: string | null
  isLink?: boolean | null
  isActive?: boolean | null
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items".
 */
export interface NavItem {
  id: number
  name: string
  urlLink?: string | null
  isLink?: boolean | null
  isSectionHeader?: boolean | null
  parent?: (number | null) | NavItem
  enable?: boolean | null
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'pages'
        value: number | Page
      } | null)
    | ({
        relationTo: 'models'
        value: number | Model
      } | null)
    | ({
        relationTo: 'banners'
        value: number | Banner
      } | null)
    | ({
        relationTo: 'maintenance-plans'
        value: number | MaintenancePlan
      } | null)
    | ({
        relationTo: 'locations'
        value: number | Location
      } | null)
    | ({
        relationTo: 'services'
        value: number | Service
      } | null)
    | ({
        relationTo: 'nav-items'
        value: number | NavItem
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  title?: T
  description?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T
              title?: T
              description?: T
              image?: T
              ctaLabel?: T
              ctaHref?: T
              id?: T
              blockName?: T
            }
        content?:
          | T
          | {
              heading?: T
              body?: T
              alignment?: T
              id?: T
              blockName?: T
            }
        mediaBlock?:
          | T
          | {
              media?: T
              caption?: T
              id?: T
              blockName?: T
            }
        cards?:
          | T
          | {
              heading?: T
              items?:
                | T
                | {
                    title?: T
                    description?: T
                    image?: T
                    href?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        accordion?:
          | T
          | {
              heading?: T
              items?:
                | T
                | {
                    question?: T
                    answer?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        callToAction?:
          | T
          | {
              heading?: T
              description?: T
              label?: T
              href?: T
              id?: T
              blockName?: T
            }
      }
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        canonicalUrl?: T
        noIndex?: T
        noFollow?: T
        socialImage?: T
        structuredData?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  code?: T
  type?: T
  passengers?: T
  transmission?: T
  year?: T
  priceBase?: T
  promoPrice?: T
  description?: T
  image?: T
  urlImage?: T
  urlTechSpec?: T
  gallery?:
    | T
    | {
        image?: T
        type?: T
        isMain?: T
        isActive?: T
        id?: T
      }
  order?: T
  enable?: T
  isProd?: T
  isDevelop?: T
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        canonicalUrl?: T
        noIndex?: T
        noFollow?: T
        socialImage?: T
        structuredData?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  section?: T
  alt?: T
  type?: T
  image?: T
  imageMobile?: T
  bannerUrl?: T
  bannerUrlMobile?: T
  videoUrl?: T
  videoMobileUrl?: T
  order?: T
  enable?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-plans_select".
 */
export interface MaintenancePlansSelect<T extends boolean = true> {
  name?: T
  code?: T
  image?: T
  image2?: T
  planImageUrl?: T
  planImageUrl2?: T
  order?: T
  enabled?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T
  address?: T
  phone?: T
  branchHours?: T
  workshopHours?: T
  googleLink?: T
  wazeLink?: T
  appleMapsLink?: T
  specialities?: T
  isBranchOffice?: T
  isRepairShop?: T
  isActive?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T
  image?: T
  url?: T
  link?: T
  page?: T
  isLink?: T
  isActive?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items_select".
 */
export interface NavItemsSelect<T extends boolean = true> {
  name?: T
  urlLink?: T
  isLink?: T
  isSectionHeader?: T
  parent?: T
  enable?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number
  ethics?: {
    text?: string | null
    ctaLabel?: string | null
    href?: string | null
  }
  servicesPage?: {
    title?: string | null
    body?: string | null
  }
  plansPage?: {
    title?: string | null
    intro?: string | null
  }
  workshopsPage?: {
    title?: string | null
    body?: string | null
    image?: (number | null) | Media
  }
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    canonicalUrl?: string | null
    noIndex?: boolean | null
    noFollow?: boolean | null
    socialImage?: (number | null) | Media
    /**
     * JSON-LD controlado para datos estructurados de Schema.org.
     */
    structuredData?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number
  logo?: (number | null) | Media
  navigation?: (number | NavItem)[] | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number
  legalText?: string | null
  socialLinks?:
    | {
        label: string
        url: string
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number
  heading?: string | null
  intro?: string | null
  featuredModels?: (number | Model)[] | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    canonicalUrl?: string | null
    noIndex?: boolean | null
    noFollow?: boolean | null
    socialImage?: (number | null) | Media
    /**
     * JSON-LD controlado para datos estructurados de Schema.org.
     */
    structuredData?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  ethics?:
    | T
    | {
        text?: T
        ctaLabel?: T
        href?: T
      }
  servicesPage?:
    | T
    | {
        title?: T
        body?: T
      }
  plansPage?:
    | T
    | {
        title?: T
        intro?: T
      }
  workshopsPage?:
    | T
    | {
        title?: T
        body?: T
        image?: T
      }
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        canonicalUrl?: T
        noIndex?: T
        noFollow?: T
        socialImage?: T
        structuredData?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T
  navigation?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  legalText?: T
  socialLinks?:
    | T
    | {
        label?: T
        url?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heading?: T
  intro?: T
  featuredModels?: T
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        canonicalUrl?: T
        noIndex?: T
        noFollow?: T
        socialImage?: T
        structuredData?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
